# From the Sentiment analysis can we predict the Rating

In [53]:
import re
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LinearRegression, SGDClassifier, LogisticRegression
from sklearn import utils, preprocessing

In [87]:
SA=pd.read_excel("../CannaConnect/Dataset/Sentiment_Analysis.xlsx")
SA=SA['Sentiment_Description']
SA.head()

0    0.164095
1    0.203125
2   -0.072619
3    0.537500
4    0.389815
Name: Sentiment_Description, dtype: float64

In [89]:
Rating=pd.read_excel("../CannaConnect/Dataset/EDA.xlsx")
Rating=Rating['Rating']
Rating.head()

0    4.0
1    4.7
2    4.4
3    4.2
4    4.6
Name: Rating, dtype: float64

In [71]:
data=pd.concat([Rating,SA],axis=1)
data.shape

(2349, 2)

In [72]:
data=data.dropna()
data.shape

(2277, 2)

In [73]:
data.head()

Rating  Sentiment_Description
0     4.0               0.164095
1     4.7               0.203125
2     4.4              -0.072619
3     4.2               0.537500
4     4.6               0.389815

In [76]:
data.dtypes

Rating                   float64
Sentiment_Description    float64
dtype: object

In [100]:
X=data[['Sentiment_Description']]
y=data[['Rating']].astype('int')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.head())
print(X_train.shape)

      Sentiment_Description
2069               0.075000
2210               0.251587
2076               0.173611
8                  0.000000
1573               0.218750
(1821, 1)


In [101]:
#Getting rid of the the index values
X_train=X_train.values
y_train=y_train.values
X_test=X_test.values
y_test=y_test.values

In [102]:
#Logistic Regression
logreg=LogisticRegression().fit(X_train, y_train)
print('Accuracy of Logistic regression classifier on training set: {:.2f}'.format(logreg.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))
pred = logreg.predict(X_test)
print('MAE of Logistic regression classifier on test set: {:.2f}'.format(mean_absolute_error(y_test, pred)))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
scores = cross_val_score(logreg, X, y, cv=10)
print("Cross-validated scores:", scores)

Accuracy of Logistic regression classifier on training set: 0.83
Accuracy of Logistic regression classifier on test set: 0.86
MAE of Logistic regression classifier on test set: 0.21
[[  0   0  11   0]
 [  0   0  17   0]
 [  0   0 392   0]
 [  0   0  36   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           3       0.00      0.00      0.00        17
           4       0.86      1.00      0.92       392
           5       0.00      0.00      0.00        36

   micro avg       0.86      0.86      0.86       456
   macro avg       0.21      0.25      0.23       456
weighted avg       0.74      0.86      0.79       456

Cross-validated scores: [0.82683983 0.83043478 0.83406114 0.8377193  0.8377193  0.8377193
 0.84070796 0.84070796 0.84070796 0.84444444]


C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', avera

In [104]:
#Decision Tree
dtc = DecisionTreeClassifier().fit(X_train, y_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'.format(dtc.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(dtc.score(X_test, y_test)))
pred = dtc.predict(X_test)
print('MAE of Decision Tree classifier on test set: {:.2f}'.format(mean_absolute_error(y_test, pred)))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
scores = cross_val_score(dtc, X, y, cv=10)
print("Cross-validated scores:", scores)

Accuracy of Decision Tree classifier on training set: 0.92
Accuracy of Decision Tree classifier on test set: 0.75
MAE of Decision Tree classifier on test set: 0.46
[[  2   0   0   9   0]
 [  0   0   0   0   0]
 [  2   0   1  14   0]
 [ 19   1  12 335  25]
 [  0   0   3  31   2]]
              precision    recall  f1-score   support

           0       0.09      0.18      0.12        11
           1       0.00      0.00      0.00         0
           3       0.06      0.06      0.06        17
           4       0.86      0.85      0.86       392
           5       0.07      0.06      0.06        36

   micro avg       0.75      0.75      0.75       456
   macro avg       0.22      0.23      0.22       456
weighted avg       0.75      0.75      0.75       456

Cross-validated scores: [0.73160173 0.78695652 0.74235808 0.73684211 0.76754386 0.73245614
 0.75221239 0.75663717 0.74336283 0.73777778]


C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


In [106]:
#KNeighbors
knn = KNeighborsClassifier().fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'.format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'.format(knn.score(X_test, y_test)))
pred = knn.predict(X_test)
print('MAE of K-NN classifier on test set: {:.2f}'.format(mean_absolute_error(y_test, pred)))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
scores = cross_val_score(knn, X, y, cv=10)
print("Cross-validated scores:", scores)

C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape

Accuracy of K-NN classifier on training set: 0.83
Accuracy of K-NN classifier on test set: 0.85
MAE of K-NN classifier on test set: 0.22
[[  0   0  11   0]
 [  0   0  17   0]
 [  0   1 389   2]
 [  0   0  36   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           3       0.00      0.00      0.00        17
           4       0.86      0.99      0.92       392
           5       0.00      0.00      0.00        36

   micro avg       0.85      0.85      0.85       456
   macro avg       0.21      0.25      0.23       456
weighted avg       0.74      0.85      0.79       456

Cross-validated scores: [0.81818182 0.82608696 0.82532751 0.8245614  0.8245614  0.80701754
 0.83628319 0.83185841 0.81415929 0.82222222]


In [107]:
#Linear Discriminant Analysis
lda = LinearDiscriminantAnalysis().fit(X_train, y_train)
print('Accuracy of LDA classifier on training set: {:.2f}'.format(lda.score(X_train, y_train)))
print('Accuracy of LDA classifier on test set: {:.2f}'.format(lda.score(X_test, y_test)))
pred = lda.predict(X_test)
print('MAE of LDA classifier on test set: {:.2f}'.format(mean_absolute_error(y_test, pred)))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
scores = cross_val_score(lda, X, y, cv=10)
print("Cross-validated scores:", scores)

Accuracy of LDA classifier on training set: 0.83
Accuracy of LDA classifier on test set: 0.86
MAE of LDA classifier on test set: 0.21
[[  0   0  11   0]
 [  0   0  17   0]
 [  0   0 392   0]
 [  0   0  36   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           3       0.00      0.00      0.00        17
           4       0.86      1.00      0.92       392
           5       0.00      0.00      0.00        36

   micro avg       0.86      0.86      0.86       456
   macro avg       0.21      0.25      0.23       456
weighted avg       0.74      0.86      0.79       456

Cross-validated scores: [0.82683983 0.83043478 0.83406114 0.8377193  0.8377193  0.8377193
 0.84070796 0.84070796 0.84070796 0.84444444]


C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expect

In [108]:
#Gaussian Naive Bayes
gnb = GaussianNB().fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.2f}'.format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'.format(gnb.score(X_test, y_test)))
pred = gnb.predict(X_test)
print('MAE of GNB classifier on test set: {:.2f}'.format(mean_absolute_error(y_test, pred)))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
scores = cross_val_score(gnb, X, y, cv=10)
print("Cross-validated scores:", scores)

Accuracy of GNB classifier on training set: 0.83
Accuracy of GNB classifier on test set: 0.86
MAE of GNB classifier on test set: 0.21
[[  0   0  11   0]
 [  0   0  17   0]
 [  0   0 392   0]
 [  0   0  36   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           3       0.00      0.00      0.00        17
           4       0.86      1.00      0.92       392
           5       0.00      0.00      0.00        36

   micro avg       0.86      0.86      0.86       456
   macro avg       0.21      0.25      0.23       456
weighted avg       0.74      0.86      0.79       456

Cross-validated scores: [0.82683983 0.83043478 0.83406114 0.8377193  0.8377193  0.8377193
 0.84070796 0.84070796 0.84070796 0.84444444]


C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
C:\Users\dastous\Anaconda3\envs\py3.6\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expect